<?php
namespace jericho\Permissions;

/**
 * Constants relating to all permissions. This class should have all constants that are in the "permissions"
 * table in the database. THE permission to SEARCH and the permission to VIEW is synonymous in the system, 
 * and is not specified as seperate permissions at the time of first development.
 * 
 * @author Jaco Koekemoer
 * Date: 2016-10-05
 */
class PermissionConstants
{
	const ADD_ACCOUNT = 'ADD_ACCOUNT';
	const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
	const VIEW_ACCOUNT = 'VIEW_ACCOUNT';
	const ADD_AREA = 'ADD_AREA';
	const UPDATE_AREA = 'UPDATE_AREA';
	const VIEW_AREA = 'VIEW_AREA';
	const ADD_ATTORNEY = 'ADD_ATTORNEY';
	const UPDATE_ATTORNEY = 'UPDATE_ATTORNEY';
	const VIEW_ATTORNEY = 'VIEW_ATTORNEY';
	const ADD_BANK = 'ADD_BANK';
	const UPDATE_BANK = 'UPDATE_BANK';
	const VIEW_BANK = 'VIEW_BANK';
	const ADD_CONTACT = 'ADD_CONTACT';
	const UPDATE_CONTACT = 'UPDATE_CONTACT';
	const VIEW_CONTACT = 'VIEW_CONTACT';
	const ADD_CONTRACTOR = 'ADD_CONTRACTOR';
	const UPDATE_CONTRACTOR = 'UPDATE_CONTRACTOR';
	const VIEW_CONTRACTOR = 'VIEW_CONTRACTOR';
	const ADD_CONTRACTOR_SERVICE = 'ADD_CONTRACTOR_SERVICE';
	const UPDATE_CONTRACTOR_SERVICE = 'UPDATE_CONTRACTOR_SERVICE';
	const VIEW_CONTRACTOR_SERVICE = 'VIEW_CONTRACTOR_SERVICE';
	const ADD_DIARY_ITEM = 'ADD_DIARY_ITEM';
	const UPDATE_DIARY_ITEM = 'UPDATE_DIARY_ITEM';
	const VIEW_DIARY_ITEM = 'VIEW_DIARY_ITEM';
	const ADD_DOCUMENT = 'ADD_DOCUMENT';
	const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
	const VIEW_DOCUMENT = 'VIEW_DOCUMENT';
	const ADD_ESTATE_AGENT = 'ADD_ESTATE_AGENT';
	const UPDATE_ESTATE_AGENT = 'UPDATE_ESTATE_AGENT';
	const VIEW_ESTATE_AGENT = 'VIEW_ESTATE_AGENT';
	const ADD_FOLLOWUP_ITEM = 'ADD_FOLLOWUP_ITEM';
	const UPDATE_FOLLOWUP_ITEM = 'UPDATE_FOLLOWUP_ITEM';
	const VIEW_FOLLOWUP_ITEM = 'VIEW_FOLLOWUP_ITEM';
	const ADD_GREATER_AREA = 'ADD_GREATER_AREA';
	const UPDATE_GREATER_AREA = 'UPDATE_GREATER_AREA';
	const VIEW_GREATER_AREA = 'VIEW_GREATER_AREA';
	const ADD_ATTORNEY_TYPE = 'ADD_ATTORNEY_TYPE';
	const UPDATE_ATTORNEY_TYPE = 'UPDATE_ATTORNEY_TYPE';
	const VIEW_ATTORNEY_TYPE = 'VIEW_ATTORNEY_TYPE';
	const ADD_CONTRACTOR_TYPE = 'ADD_CONTRACTOR_TYPE';
	const UPDATE_CONTRACTOR_TYPE = 'UPDATE_CONTRACTOR_TYPE';
	const VIEW_CONTRACTOR_TYPE = 'VIEW_CONTRACTOR_TYPE';
	const ADD_ESTATE_AGENT_TYPE = 'ADD_ESTATE_AGENT_TYPE';
	const UPDATE_ESTATE_AGENT_TYPE = 'UPDATE_ESTATE_AGENT_TYPE';
	const VIEW_ESTATE_AGENT_TYPE = 'VIEW_ESTATE_AGENT_TYPE';
	const ADD_MARITAL_STATUS = 'ADD_MARITAL_STATUS';
	const UPDATE_MARITAL_STATUS = 'UPDATE_MARITAL_STATUS';
	const VIEW_MARITAL_STATUS = 'VIEW_MARITAL_STATUS';
	const ADD_TITLE = 'ADD_TITLE';
	const UPDATE_TITLE = 'UPDATE_TITLE';
	const VIEW_TITLE = 'VIEW_TITLE';
	const ADD_TRANSACTION_TYPE = 'ADD_TRANSACTION_TYPE';
	const UPDATE_TRANSACTION_TYPE = 'UPDATE_TRANSACTION_TYPE';
	const VIEW_TRANSACTION_TYPE = 'VIEW_TRANSACTION_TYPE';
	const ADD_MILESTONE = 'ADD_MILESTONE';
	const UPDATE_MILESTONE = 'UPDATE_MILESTONE';
	const VIEW_MILESTONE = 'VIEW_MILESTONE';
	const ADD_NOTE = 'ADD_NOTE';
	const UPDATE_NOTE = 'UPDATE_NOTE';
	const VIEW_NOTE = 'VIEW_NOTE';
	const ADD_PERMISSION = 'ADD_PERMISSION';
	const UPDATE_PERMISSION = 'UPDATE_PERMISSION';
	const VIEW_PERMISSION = 'VIEW_PERMISSION';
	const ADD_PROPERTY = 'ADD_PROPERTY';
	const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
	const VIEW_PROPERTY = 'VIEW_PROPERTY';
	const ADD_PROPERTY_FLIP = 'ADD_PROPERTY_FLIP';
	const UPDATE_PROPERTY_FLIP = 'UPDATE_PROPERTY_FLIP';
	const VIEW_PROPERTY_FLIP = 'VIEW_PROPERTY_FLIP';
	const ADD_PROPERTY_TYPE = 'ADD_PROPERTY_TYPE';
	const UPDATE_PROPERTY_TYPE = 'UPDATE_PROPERTY_TYPE';
	const VIEW_PROPERTY_TYPE = 'VIEW_PROPERTY_TYPE';
	const ADD_ROLE = 'ADD_ROLE';
	const UPDATE_ROLE = 'UPDATE_ROLE';
	const VIEW_ROLE = 'VIEW_ROLE';
	const ADD_SUBURB = 'ADD_SUBURB';
	const UPDATE_SUBURB = 'UPDATE_SUBURB';
	const VIEW_SUBURB = 'VIEW_SUBURB';
	const ADD_TRANSACTION = 'ADD_TRANSACTION';
	const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
	const VIEW_TRANSACTION = 'VIEW_TRANSACTION';
	const ADD_USER = 'ADD_USER';
	const UPDATE_USER = 'UPDATE_USER';
	const VIEW_USER = 'VIEW_USER';
	const LINK_ATTORNEY_CONTACT = 'LINK_ATTORNEY_CONTACT';
	const DELETE_ATTORNEY_CONTACT_LINK = 'DELETE_ATTORNEY_CONTACT_LINK';
	const VIEW_PROPERTY_FLIP_ATTORNEYS = 'VIEW_PROPERTY_FLIP_ATTORNEYS';
	const LINK_ESTATE_AGENT_CONTACT = 'LINK_ESTATE_AGENT_CONTACT';
	const DELETE_ESTATE_AGENT_CONTACT_LINK = 'DELETE_ESTATE_AGENT_CONTACT_LINK';
	const VIEW_PROPERTY_FLIP_ESTATE_AGENTS = 'VIEW_PROPERTY_FLIP_ESTATE_AGENTS';
	const LINK_CONTRACTOR_CONTACT = 'LINK_CONTRACTOR_CONTACT';
	const DELETE_CONTRACTOR_CONTACT_LINK = 'DELETE_CONTRACTOR_CONTACT_LINK';
	const VIEW_PROPERTY_FLIP_CONTRACTORS = 'VIEW_PROPERTY_FLIP_CONTRACTORS';
	const LINK_BANK_CONTACT = 'LINK_BANK_CONTACT';
	const DELETE_BANK_CONTACT_LINK = 'DELETE_BANK_CONTACT_LINK';
	const VIEW_PROPERTY_FLIP_BANKS = 'VIEW_PROPERTY_FLIP_BANKS';
	const DOWNLOAD_DOCUMENT = 'DOWNLOAD_DOCUMENT';
	const SELF_ALLOCATE_DIARY_ITEM = 'SELF_ALLOCATE_DIARY_ITEM';
	const VIEW_LEADS_TO_SALES_REPORT = 'VIEW_LEADS_TO_SALES_REPORT';
	const VIEW_AMOUNT_OF_LEADS_ACTIONED_REPORT = 'VIEW_AMOUNT_OF_LEADS_ACTIONED_REPORT';
	const VIEW_LEADS_PER_AREA_REPORT = 'VIEW_LEADS_PER_AREA_REPORT';
	const VIEW_PROFIT_AND_LOSS_BY_DATE_REPORT = 'VIEW_PROFIT_AND_LOSS_BY_DATE_REPORT';
	const VIEW_TOTALS_PER_STATUS_REPORT = 'VIEW_TOTALS_PER_STATUS_REPORT';
	const VIEW_AUDIT_TRAIL = 'VIEW_AUDIT_TRAIL';
}